controller_list:
  - name: fake_right_arm_controller
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7
  - name: fake_left_arm_controller
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
  - name: fake_right_hand_controller
    joints:
      - right_finger1_joint_base
      - right_finger1_joint1
      - right_finger1_joint2
      - right_finger2_joint_base
      - right_finger2_joint1
      - right_finger2_joint2
      - right_finger3_joint1
      - right_finger3_joint2
  - name: fake_left_hand_controller
    joints:
      - left_finger1_joint_base
      - left_finger1_joint1
      - left_finger1_joint2
      - left_finger2_joint_base
      - left_finger2_joint1
      - left_finger2_joint2
      - left_finger3_joint1
      - left_finger3_joint2
  - name: fake_arms_controller
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7
  - name: fake_hands_controller
    joints:
      - left_finger1_joint_base
      - left_finger1_joint1
      - left_finger1_joint2
      - left_finger2_joint_base
      - left_finger2_joint1
      - left_finger2_joint2
      - left_finger3_joint1
      - left_finger3_joint2
      - right_finger1_joint_base
      - right_finger1_joint1
      - right_finger1_joint2
      - right_finger2_joint_base
      - right_finger2_joint1
      - right_finger2_joint2
      - right_finger3_joint1
      - right_finger3_joint2