# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  left_finger1_joint1:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  left_finger1_joint2:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  left_finger1_joint_base:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  left_finger2_joint1:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  left_finger2_joint2:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  left_finger2_joint_base:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  left_finger3_joint1:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  left_finger3_joint2:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  left_joint1:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  left_joint2:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  left_joint3:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  left_joint4:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  left_joint5:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  left_joint6:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  left_joint7:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  right_finger1_joint1:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  right_finger1_joint2:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  right_finger1_joint_base:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  right_finger2_joint1:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  right_finger2_joint2:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  right_finger2_joint_base:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  right_finger3_joint1:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  right_finger3_joint2:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  right_joint1:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  right_joint2:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  right_joint3:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  right_joint4:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  right_joint5:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  right_joint6:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0
  right_joint7:
    has_velocity_limits: true
    max_velocity: 0.87
    has_acceleration_limits: false
    max_acceleration: 0